"""Added index to path

Revision ID: fafc54af06f8
Revises: 3da5f06f5a16
Create Date: 2024-06-15 03:26:10.110649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fafc54af06f8'
down_revision = '3da5f06f5a16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service_images_path_key', 'service_images', type_='unique')
    op.create_index(op.f('ix_service_images_path'), 'service_images', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_images_path'), table_name='service_images')
    op.create_unique_constraint('service_images_path_key', 'service_images', ['path'])
    # ### end Alembic commands ###
