"""Added local_path

Revision ID: 6d2ab85fff8e
Revises: fafc54af06f8
Create Date: 2024-06-16 01:11:23.252583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2ab85fff8e'
down_revision = 'fafc54af06f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_images', sa.Column('local_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_images', 'local_path')
    # ### end Alembic commands ###
